from typing import TypeAlias

class Recognizer:
    def __init__(self) -> None: ...
    def listen(self, source: AudioSource, timeout: int | None = ..., phrase_time_limit: int | None = ...) -> AudioData: ...
    def recognize_google(self, audio_data: AudioData, key: str | None = ..., language: str = ..., show_all: bool = ...) -> str: ...
    def adjust_for_ambient_noise(self, source: AudioSource, duration: float = ...) -> None: ...

class AudioSource: ...
class Microphone(AudioSource):
    def __init__(self, device_index: int | None = ..., chunk_size: int = ...) -> None: ...
    def __enter__(self) -> "Microphone": ...
    def __exit__(self, exc_type, exc_val, exc_tb) -> None: ...

class AudioData: ...

class WaitTimeoutError(Exception): ...
class UnknownValueError(Exception): ...
class RequestError(Exception): ...

